version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"

  - package-ecosystem: "cargo"
    directory: "/toml-merge"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"
